### ISSUE TITLE
terraform deployment throws error on 2nd execution

### ISSUE THREAD

**Issue by dannystommen** [Snowflake-Labs/roleout#11]
After the advice to use terraform deployment instead of SQL deployment (https://github.com/Snowflake-Labs/roleout/issues/6), I've been trying to get it working with terraform.

When running it on an empty environment, it creates everything as expected. But when running it the 2nd time, it's trying to do something with stored producedures and STORE_CLASSIFICATION. All other resources are skipt (as expected).

[apply_output.txt](https://github.com/Snowflake-Labs/roleout/files/11788846/apply_output.txt)

Any idea what might be causing this?

I'm executing the following commands:

roleout terraform deploy -c roleout_config.yml -o roleout_scripts
cd roleout_scripts
terraform init
terraform validate
terraform plan
terraform apply -auto-approve

And this is the roleout_config: 
[roleout_config.yml.txt](https://github.com/Snowflake-Labs/roleout/files/11788865/roleout_config.yml.txt)

**Comment by sfc-gh-ckite** [comment]
@dannystommen this was fixed by version 2.0 of Roleout. However there are [other Terraform provider bugs](https://github.com/Snowflake-Labs/roleout/discussions/13) currently making provisioning challenging or impossible.

The next version of Roleout will address these issues by using [snowflake_grant_privileges_to_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role) from the new 0.68 version of the Terraform provider.
