### ISSUE TITLE
Upgrade terraform provider version

### ISSUE THREAD

**Issue by markns** [Snowflake-Labs/roleout#15]
There is a bug with the import of databases using older versions of the Terraform provider:

https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1868

Upgrading the provider version in snowflake.tf to 0.68.1 fixed the issue for me, but each time `roleout-cli terraform deploy` is run it reverts the version to 0.64.0. 

Would it be possible to make the terraform provider version user configurable?

**Comment by sfc-gh-ckite** [comment]
You can indeed change the version of the Terraform provider by modifying it in the `snowflake.tf` file. 

Currently because of the bug you mentioned and others ([discussed here](https://github.com/Snowflake-Labs/roleout/discussions/13)) I am working on rewriting the Terraform generation code in Roleout to use [snowflake_grant_privileges_to_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_role) which was just introduced in 0.68.
